### ISSUE TITLE
Doesn't build with poppler 0.86.1

### ISSUE THREAD

**Issue by seb128** [trueroad/extractpdfmark#2]
The current version fails to build with the new poppler, build log example

https://launchpadlibrarian.net/469668101/buildlog_ubuntu-focal-amd64.extractpdfmark_1.1.0-1ubuntu3_BUILDING.txt.gz

**Comment by trueroad** [comment]
It seems that your environment does not have poppler-cpp.
In your build log,

```
configure: selecting for --with-poppler=auto
configure:  trying for cpp (poppler-cpp >= 0.74.0)
checking for POPPLER_CPP... no
configure:  trying for core (poppler >= 0.48.0)
checking for POPPLER... yes
configure: use --with-poppler=core
```

Please use poppler-cpp interface if you use poppler-0.74.0 or above.
Maybe libpoppler-cpp-dev package is required for Ubuntu.

**Comment by seb128** [comment]
Thanks for pointing that out! Indeed adding that Build-Depends fixes it, weird that it built fine without it until poppler 0.85 though...
